broker_url: 'tcp://10.192.36.190:61613'
jwt_expiry: '+2 hour'
gemini_url: 'http://10.192.36.190/gemini'
gemini_pseudo_bundles:
  'asu_repository_item:node': 'asu_repository_item:node'
  'islandora_object:node': 'islandora_object:node'
  'audio:media': 'audio:media'
  'file:media': 'file:media'
  'image:media': 'image:media'
  'video:media': 'video:media'
