field.formatter.settings.searchable_entity_formatter:
  type: mapping
  label: 'Searchable Entity Formatter settings'
  mapping:
    search_link:
      type: string
      label: 'Search path'
    search_var:
      type: string
      label: 'Search variable'
    search_term:
      type: boolean
      label: 'Use label as search term'